# Inhaltsverzeichnis 

- **Numpy Aufgaben**
    - **Aufgabe 1 - Arrays definieren**
    - **Aufgabe 2 - Addition**
    - **Aufgabe 3 - Multiplikation**
    - **Aufgabe 4 - Rechnen mit Arrays**
    - **Aufgabe 5 - Weitere Funktionen**
    - **Aufgabe 6 - Slicing**
    - **Aufgabe 7 - Form ändern**


# Numpy Aufgaben

In [2]:
import numpy as np

## Aufgabe 1 - Arrays definieren

- Definiere einen Vektor X: 

\begin{align}
\mathbf{X} = \pmatrix{0 \\ 0 \\ 0 \\ 0 \\ 0}
\end{align}

und einen Vektor Y:

\begin{align}
\mathbf{Y} = \pmatrix{1 \\ 1 \\ 1 \\ 1 \\ 1}
\end{align}



In [4]:

X = np.zeros((5,1))
Y = np.ones((5,1))

print(X,"\n",Y)

# Schreibe dein Code hier

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]] 
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


- Erstelle die Identitätsmatrix der Größe 3:
\begin{align}
I = 
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{bmatrix}
\end{align}

In [11]:

I = np.eye(3)

print(I)

# Schreibe dein Code hier

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


- Erstelle folgendes Array
\begin{align}
C = 
\begin{bmatrix}
5 & 5 & 5 \\
5 & 5 & 5 \\
5 & 5 & 5 \\
\end{bmatrix}
\end{align}
auf möglichst einfache Art.

In [13]:

C = np.array([5]*9).reshape(3,3)

print(C)

# Schreibe dein Code hier

[[5 5 5]
 [5 5 5]
 [5 5 5]]


- Erstelle folgendes Array
\begin{align}
D = 
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \\
\end{bmatrix}
\end{align}
auf möglichst einfach Art.

In [15]:

D = np.arange(1,10).reshape(3,3)

print(D)

# Schreibe dein Code hier

[[1 2 3]
 [4 5 6]
 [7 8 9]]


- Definiere zwei Arrays $A$ und $B$ mit folgenden Elementen:
\begin{align}
A=
\begin{bmatrix}
7 & 8  \\
11 & 12  \\
3 & 0  \\
\end{bmatrix}
, \qquad B = 
\begin{bmatrix}
0 & 1 \\
2 & 9 \\
3 & 7  \\
\end{bmatrix}
\end{align}

In [16]:

A = np.array([[7,8],[11,12],[3,0]])
B = np.array([[0,1],[2,9],[3,7]])

print(A, "\n",B)

# Schreibe dein Code hier

[[ 7  8]
 [11 12]
 [ 3  0]] 
 [[0 1]
 [2 9]
 [3 7]]


## Aufgabe 2 - Addition

- Addiere die Arrays $A$ und $B$ miteinander. 

In [19]:

C = A + B
print(C)

# Schreibe dein Code hier

[[ 7  9]
 [13 21]
 [ 6  7]]


- Berechne die Summe des Arrays $A$ mit der Funktion [numpy.sum](https://numpy.org/doc/stable/reference/generated/numpy.sum.html): 

    - Aller Elemente
    - Entlang der Spalten
    - Entlang der Zeilen

In [22]:

# alle elemente:
summe_alle = np.sum(A)
print(summe_alle)

#alle spalten:
summe_spalt = np.sum(A,axis=0)
print(summe_spalt)

#alle zeilen:
summe_zeile = np.sum(A,axis=1)
print(summe_zeile)

# Schreibe dein Code hier

41
[21 20]
[15 23  3]


## Aufgabe 3 - Multiplikation

- Multipliziere die Arrays $A$ und $B$ **elementweise**.

In [23]:

multipl = A * B
print(multipl)

# Schreibe dein Code hier

[[  0   8]
 [ 22 108]
 [  9   0]]


## Aufgabe 4 - Rechnen mit Arrays

- Finde das Array $C$, so das gilt $A+C = B$.

In [25]:

C = B - A
print(C)

# Schreibe dein Code hier

[[-7 -7]
 [-9 -3]
 [ 0  7]]


## Aufgabe 5 - Weitere Funktionen

- Berechne das arithmetische Mittel (`mean`) von Array $A$ für entlang der ersten Achse.

In [33]:

ari_mittel01 = np.mean(A[0,:])  # 1.zeilenachse,horizontal
ari_mittel02 = np.mean(A[:,0])  # 1.spaltenachse, vertikal
print(ari_mittel01,"\n",ari_mittel02)

# Schreibe dein Code hier

7.5 
 7.0


- Berechne den Logarithmus (`log`) des Arrays $A$.

> <span style="color:blue"> **_INFO:_** </span> Lass dich nicht irritieren, wenn numpy Warnungen ausgibt. Der Grund dafür ist, dass der Logarithmus bei 0 unendlich negativ wird: 

\begin{align}
\log(0)  = - \infty
\end{align}


In [34]:

log_A = np.log(A)
print(log_A)

# Schreibe dein Code hier

[[1.94591015 2.07944154]
 [2.39789527 2.48490665]
 [1.09861229       -inf]]


C:\Users\dietm\AppData\Local\Temp\ipykernel_7436\506244182.py:1: RuntimeWarning: divide by zero encountered in log
  log_A = np.log(A)


- Berechne das Maximum (`max`) von Array $A$ entlang der ersten Achse.

In [35]:

max_achse01 = np.max(A[0,:])    # 1.zeilenachse,horizontal
max_achse02 = np.max(A[:,0])    # 1.spaltenachse, vertikal
print(max_achse01,"\n",max_achse02)

# Schreibe dein Code hier

8 
 11


## Aufgabe 6 - Slicing

- Wie müssen wir die Indizes beim Slicing wählen, um aus Array D, folgendes Array zu erhalten:

\begin{align}
E = 
\begin{bmatrix}
1 & 2 \\
4 & 5 \\
\end{bmatrix}
\end{align}

In [38]:

D = np.arange(1,10).reshape(3,3)
E = D[:-1,:-1]
print(E)

# Schreibe dein Code hier

[[1 2]
 [4 5]]


- Wie müssen wir die Indizes beim Slicing wählen, um aus Array D, folgendes Array zu erhalten:

\begin{align}
F=
\begin{bmatrix}
1 & 3 \\
7 & 9 \\
\end{bmatrix}
\end{align}

In [39]:

F = D[::2,::2]
print(F)

# Schreibe dein Code hier

[[1 3]
 [7 9]]


## Aufgabe 7 - Form ändern

- Erstelle das Array:
\begin{align}
G = 
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
5 & 6 
\end{bmatrix}
\end{align}



In [41]:

G = np.arange(1,7).reshape(3,2)
print(G)

# Schreibe dein Code hier

[[1 2]
 [3 4]
 [5 6]]


- Lass dir die Form (*shape*) von $G$ ausgeben.

In [42]:

print(G.shape)

# Schreibe dein Code hier

(3, 2)


- Erstelle ein neues Array, welches die **Transponierte Matrix** von $G$ ist.

In [83]:

G = np.arange(1,7).reshape(3,2)
#print(np.transpose(G))
print(G)
spalten_01 = np.concatenate(G,axis=0)
print(spalten_01)
#erste_zeile = spalten_01[::2]
#print(erste_zeile)
#zweite_zeile = spalten_01[1:6:2]
#print(zweite_zeile)
gesamt_zeile = np.array([spalten_01[::2],spalten_01[1:6:2]])
print(gesamt_zeile)

# Schreibe dein Code hier

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[[1 3 5]
 [2 4 6]]


- Erstelle ein neues Array, welches das Array $G$ in "flacher" Form ist. Welche Dimension hat das neue Array?

In [20]:

print(G.flatten())

# Schreibe dein Code hier

[1 2 3 4 5 6]


- Überführe $G$ in die Form `(6,1)`

In [81]:

G = np.arange(1,7).reshape(6,1)
print(G)

# Schreibe dein Code hier

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
