# Inhaltsverzeichnis 

- **Aufgaben: Logistische Regression**
    - **Aufgabe 1: Imports**
    - **Aufgabe 2: Daten verstehen**
    - **Aufgabe 3: Daten aufteilen**
    - **Aufgabe 4: Modell trainieren & evaluieren**
    - **Aufgabe 5: Falsche Vorhersagen**


# Aufgaben: Logistische Regression

In dieser Aufgabe wollen wir eine Logistische Regression durchführen für den [Iris-Datensatz](https://en.wikipedia.org/wiki/Iris_flower_data_set).  Wir werden dafür erstmal die nötigen Bibliotheken importieren und die Daten ausgeben. Danach wird ein Modell auf dem Trainingsdatensatz trainiert und die Genauigkeit auf den Testdatensatz berechnet. Als letzten wollen wir uns noch die Samples anzeigen lassen, welche von unserem Modell _nicht_ korrekt klassifiziert wurden.

## Aufgabe 1: Imports

- Importiere `numpy` und `pandas`.
- Importiere `seaborn` und `matplotlib.pyplot`.
- Importiere das Modul [`datasets`](https://scikit-learn.org/stable/modules/classes.html?highlight=dataset#module-sklearn.datasets) von `sklearn`.
- Importiere das Modell [`LogisticRegression`](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html) aus [`sklearn.linear_model`](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.linear_model).
- Importiere die Funktion [`train_test_split`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html) aus `sklearn.model_selection`.
- Importiere die Funktion [`accuracy_score`](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html#sklearn.metrics.accuracy_score) aus dem Modul [`sklearn.metrics`](https://scikit-learn.org/stable/modules/classes.html?highlight=metrics#module-sklearn.metrics).
- Lies die Datei `iris.csv` aus dem Kursbereich als ein Pandas [DataFrame](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html) mit einem `\t` (*Tabulator*) Trennzeichen (delimiter) ein.

In [1]:
# Schreibe deinen Code hier

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
%matplotlib inline
sns.set_theme()

# Schreibe deinen Code hier

In [2]:

iris = pd.read_csv("iris.csv",delimiter="\t")


In [3]:

iris.head(3)


sepal_length  sepal_width  petal_length  petal_width  class
0           5.1          3.5           1.4          0.2      0
1           4.9          3.0           1.4          0.2      0
2           4.7          3.2           1.3          0.2      0

## Aufgabe 2: Daten verstehen

- Gib das Shape des Datensatzes auf der Konsole aus.
- Wieviele Samples gibt es im Datensatz? Wieviele Features haben die Daten?
- Gib die ersten 3 Zeilen des Datensatzes auf der Konsole aus. 
- Gib den Mittelwert der Spalten auf der Konsole aus.
- Gib den maximalen und minimalen Wert der Spalten auf der Konsole aus.

In [4]:
# Schreibe deinen Code hier

# 150 samples und 5 features
iris.shape

# Schreibe deinen Code hier

(150, 5)

In [5]:
iris.describe()

sepal_length  sepal_width  petal_length  petal_width       class
count    150.000000   150.000000    150.000000   150.000000  150.000000
mean       5.843333     3.057333      3.758000     1.199333    1.000000
std        0.828066     0.435866      1.765298     0.762238    0.819232
min        4.300000     2.000000      1.000000     0.100000    0.000000
25%        5.100000     2.800000      1.600000     0.300000    0.000000
50%        5.800000     3.000000      4.350000     1.300000    1.000000
75%        6.400000     3.300000      5.100000     1.800000    2.000000
max        7.900000     4.400000      6.900000     2.500000    2.000000

In [6]:

iris_01 = iris.describe()


In [7]:

iris_01.loc["mean"]


sepal_length    5.843333
sepal_width     3.057333
petal_length    3.758000
petal_width     1.199333
class           1.000000
Name: mean, dtype: float64

In [8]:
iris_01.loc["min"]

sepal_length    4.3
sepal_width     2.0
petal_length    1.0
petal_width     0.1
class           0.0
Name: min, dtype: float64

In [9]:
iris_01.loc["max"]

sepal_length    7.9
sepal_width     4.4
petal_length    6.9
petal_width     2.5
class           2.0
Name: max, dtype: float64

## Aufgabe 3: Daten aufteilen

- Erstelle ein Numpy Array `X` mit den 4 Spalten aus dem Datensatz.
- Erstelle ein Numpy Array `y` mit der letzten Spalte aus dem Datensatz (dem Target).
- Teile die Daten mit der Funktion `train_test_split` in `X_train, X_test, y_train, y_test` auf. Hierbei sollten 80% die Trainingsdaten und die restlichen 20% die Testdaten ausmachen.

> <span style="color:red"> **_WICHTIG:_** </span> Damit die Ergebnisse vergleichbar sind, benutze beim `train_test_split` das Argument `random_state=301`. Dadurch erhalten wir immer den selben Split der Daten.

- Gib die Dimensionen von `X`, `X_train` und `X_test` auf der Konsole aus.

In [10]:

X = np.array(iris[["sepal_length","sepal_width","petal_length","petal_width"]])


In [13]:

y = np.array(iris["class"])


In [16]:
# Schreibe deinen Code hier

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=301)

# Schreibe deinen Code hier

In [20]:

print(X.shape)
print(X_train.shape)
print(X_test.shape)


(150, 4)
(120, 4)
(30, 4)


## Aufgabe 4: Modell trainieren & evaluieren

- Erstelle ein Modell der Klasse `LogisticRegression`.
- Trainiere das Modell anhand der Trainingsdaten `X_train` und `y_train`.
- Nutze die Methode `predict` des Regressionsmodells auf die Testdaten `X_test` und speichere die ausgegebene Labels in `y_pred_test`.
- Gib den `accuracy_score` der Predictions für die Testdaten auf der Konsole aus.

In [21]:
# Schreibe deinen Code hier

logReg = LogisticRegression()

# Schreibe deinen Code hier

In [22]:

logReg.fit(X_train,y_train)


C:\Users\dietm\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [23]:

y_pred_test = logReg.predict(X_test)


In [25]:

accuracy_score(y_test,y_pred_test)


0.9333333333333333

## Aufgabe 5: Falsche Vorhersagen

- Gib die Samples aus `X_test` aus, welche **falsch** klassifiziert wurden. Überlege dir dazu, wie man das erreichen kann.

In [26]:
y_test

array([2, 0, 1, 1, 0, 2, 2, 0, 0, 1, 2, 1, 0, 1, 0, 0, 0, 2, 2, 1, 0, 1,
       0, 0, 0, 2, 0, 2, 1, 2], dtype=int64)

In [27]:
y_pred_test

array([2, 0, 1, 2, 0, 2, 2, 0, 0, 1, 2, 2, 0, 1, 0, 0, 0, 2, 2, 1, 0, 1,
       0, 0, 0, 2, 0, 2, 1, 2], dtype=int64)

In [41]:
# Schreibe deinen Code hier

def fehler_find(array01,array02):
    
    liste_index = []
    
    for i in range(len(array01)):
        if array01[i] != array02[i]:
            liste_index.append(i)
            
    return X_test[liste_index]
            

# Schreibe deinen Code hier

In [42]:

fehler_find(y_pred_test,y_test)


array([[6. , 2.7, 5.1, 1.6],
       [6.7, 3. , 5. , 1.7]])